config/routes.rb
Rails.application.routes.draw do
  resources :comment_files
  resources :comments
  resources :tasks
  resources :projects
  devise_for :users

  # define home page
  root to: 'pages#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define the permissions for the users.
    user ||= User.new # guest user (not logged in)

    if user.admin?
      # Admin can manage everything
      can :manage, :all
    else
      can :manage, Project, user_id: user.id
      can :manage, Task, user_id: user.id
      can :manage, Comment, user_id: user.id
      # can :read, :all, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # DB Relations
  has_many :comment_files, dependent: :destroy
  belongs_to :user
  belongs_to :task

  # Validation
  validates :comment, presence: true
end

app/models/comment_file.rb
class CommentFile < ApplicationRecord
  # DB Relations
  belongs_to :comment

  # Validation
  validates :file, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  # DB Relations
  has_many :tasks, dependent: :destroy
  belongs_to :user

  # Validation
  validates :name, :status, presence: true

  # Enum
  enum status: %i[pending in_progress finished]
end

app/models/task.rb
class Task < ApplicationRecord
  # DB Relations
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :project

  # Validation
  validates :title, :status, :deadline, presence: true

  # Enum
  enum status: %i[pending in_progress finished]
  enum priority: %i[high normal low]
end

app/models/user.rb
class User < ApplicationRecord
  # DB Relations
  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validation
  validates :first_name, :last_name, :email, presence: true

  # Get full name
  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
  # Authenticate users
  # before_action :authenticate_user!
end

app/controllers/comment_files_controller.rb
class CommentFilesController < ApplicationController
  before_action :set_comment_file, only: %i[show edit update destroy]

  # GET /comment_files
  def index
    @comment_files = CommentFile.all
  end

  # GET /comment_files/1
  def show; end

  # GET /comment_files/new
  def new
    @comment_file = CommentFile.new
  end

  # GET /comment_files/1/edit
  def edit; end

  # POST /comment_files
  def create
    @comment_file = CommentFile.new(comment_file_params)

    if @comment_file.save
      redirect_to @comment_file, notice: 'Comment file was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comment_files/1
  def update
    if @comment_file.update(comment_file_params)
      redirect_to @comment_file, notice: 'Comment file was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comment_files/1
  def destroy
    @comment_file.destroy
    redirect_to comment_files_url, notice: 'Comment file was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment_file
    @comment_file = CommentFile.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def comment_file_params
    params.require(:comment_file).permit(:comment_id, :file)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  # GET /comments for current user
  def index
    @comments = current_user.comments
  end

  # GET /comments/1
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
    @tasks = Task.all
  end

  # GET /comments/1/edit
  def edit
    @tasks = Task.all
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:comment).permit(:task_id, :comment).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # home page
  def home; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  # GET /projects for current user
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:name, :details, :status).merge(user: current_user)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  # GET /tasks for current user
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
    @projects = Project.all
  end

  # GET /tasks/1/edit
  def edit
    @projects = Project.all
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def task_params
    params.require(:task).permit(:title, :details, :priority, :status, :deadline, :project_id).merge(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_files_helper.rb
module CommentFilesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comment_files/_form.html.erb
<%= form_with(model: comment_file, local: true) do |form| %>
  <% if comment_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment_file.errors.count, "error") %> prohibited this comment_file from being saved:</h2>

      <ul>
      <% comment_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.text_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comment_files/edit.html.erb
<h1>Editing Comment File</h1>

<%= render 'form', comment_file: @comment_file %>

<%= link_to 'Show', @comment_file %> |
<%= link_to 'Back', comment_files_path %>

app/views/comment_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comment Files</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_files.each do |comment_file| %>
      <tr>
        <td><%= comment_file.comment %></td>
        <td><%= comment_file.file %></td>
        <td><%= link_to 'Show', comment_file %></td>
        <td><%= link_to 'Edit', edit_comment_file_path(comment_file) %></td>
        <td><%= link_to 'Destroy', comment_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment File', new_comment_file_path %>

app/views/comment_files/new.html.erb
<h1>New Comment File</h1>

<%= render 'form', comment_file: @comment_file %>

<%= link_to 'Back', comment_files_path %>

app/views/comment_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment_file.comment %>
</p>

<p>
  <strong>File:</strong>
  <%= @comment_file.file %>
</p>

<%= link_to 'Edit', edit_comment_file_path(@comment_file) %> |
<%= link_to 'Back', comment_files_path %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :task_id %>
    <%= form.select :task_id, options_from_collection_for_select(@tasks, :id, :title, comment.task_id), {include_blank: true}, {required: 'true', class: 'form-control' , placeholder: 'Select task'} %>
  </div>

  <div class="field form-group">
    <%= form.label :comment %>
    <%= form.text_field :comment, class: 'form-control', placeholder: 'comment', required: true %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary' %>

<br>

<!--box-->
<div class="box">
  <!--box-header-->
  <div class="box-header">
    <h3 class="box-title">
      Comments
      <small>( <%=pluralize(@comments.count,'comment')%> )</small>
    </h3>
  </div><!--box-header-->

  <!--box-body-->
  <div class="box-body no-padding">
    <table class="table table-striped">
      <tbody>
        <tr>
          <th>Project</th>
          <th>Task</th>
          <th>User</th>
          <th>Comment</th>
          <th colspan="3"></th>
        </tr>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.task.project.name %></td>
            <td><%= comment.task.title %></td>
            <td><%= comment.user.full_name %></td>
            <td><%= comment.comment %></td>
            <td>
              <% if can? :read, comment %>
                <%= link_to 'Show', comment %>
              <% end %>
            </td>
            <td>
              <% if can? :update, comment %>
                <%= link_to 'Edit', edit_comment_path(comment) %>
              <% end %>
            </td>
            <td>
              <% if can? :destroy, comment %>
                <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!--box-body-->
</div><!--box-->

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>User:</strong>
  <%= @comment.user.full_name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @comment.task.project.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @comment.task.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<% if can? :update, @comment %>
  <%= link_to 'Edit', edit_comment_path(@comment) %> |
<% end %>
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--container-->
    <div class="container">

      <%= render 'shared/navbar' %>
      <%= render 'shared/notice' %>

      <%= yield %>
    </div><!--container-->
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page</h1>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Project name', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: 'form-control', placeholder: 'Project details', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= form.select :status, { Pending: 'pending', In_Progress: 'in_progress', Finished: 'finished' }, { selected: project.status }, class: 'form-control', required: true %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<% if can? :read, @project %>
  <%= link_to 'Show', @project %> |
<% end %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

<br>

<!--box-->
<div class="box">
  <!--box-header-->
  <div class="box-header">
    <h3 class="box-title">
      Projects
      <small>( <%=pluralize(@projects.count,'project')%> )</small>
    </h3>
  </div><!--box-header-->

  <!--box-body-->
  <div class="box-body no-padding">
    <table class="table table-striped">
      <tbody>
        <tr>
          <th>User</th>
          <th>Project</th>
          <th>Details</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.user.full_name %></td>
            <td><%= project.name %></td>
            <td><%= project.details %></td>
            <td><%= project.status %></td>
            <td>
              <% if can? :read, project %>
                <%= link_to 'Show', project %>
              <% end %>
            </td>
            <td>
              <% if can? :update, project %>
                <%= link_to 'Edit', edit_project_path(project) %>
              <% end %>
            </td>
            <td>
              <% if can? :destroy, project %>
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!--box-body-->
</div><!--box-->

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>User:</strong>
  <%= @project.user.full_name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<% if can? :update, @project %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>

app/views/shared/_navbar.html.erb
<br><br>
<div class="col-md-12">
  <% if current_user %>
    Hello: <%=current_user.full_name %>
    |
    role:
    <%=current_user.admin == true ? "Admin" : "User" %>
    |
    <%=link_to projects_path do %> projects <% end %>
    |
    <%=link_to tasks_path do %> tasks <% end %>
    |
    <%=link_to comments_path do %> comments <% end %>
    |
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

  <% else %>
    <%= link_to('Login', new_user_session_path) %>
  <% end %>
</div>
<br><br>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-success notice" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :project_id %>
    <%= form.select :project_id, options_from_collection_for_select(@projects, :id, :name, task.project_id), {include_blank: true}, {required: 'true', class: 'form-control' , placeholder: 'Select project'} %>
  </div>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Project name', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: 'form-control', placeholder: 'Project name', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :priority %>
    <%= form.select :priority, { High: 'high', Normal: 'normal', Low: 'low' }, { selected: task.priority }, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= form.select :status, { Pending: 'pending', In_Progress: 'in_progress', Finished: 'finished' }, { selected: task.status }, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<% if can? :read, @task %>
  <%= link_to 'Show', @task %> |
<% end %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>

<br>

<!--box-->
<div class="box">
  <!--box-header-->
  <div class="box-header">
    <h3 class="box-title">
      Tasks
      <small>( <%=pluralize(@tasks.count,'task')%> )</small>
    </h3>
  </div><!--box-header-->

  <!--box-body-->
  <div class="box-body no-padding">
    <table class="table table-striped">
      <tbody>
        <tr>
          <th>User</th>
          <th>Task</th>
          <th>Project</th>
          <th>Priority</th>
          <th>Status</th>
          <th>Deadline</th>
          <th colspan="3"></th>
        </tr>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.user.full_name %></td>
            <td><%= task.title %></td>
            <td><%= task.project.name %></td>
            <td><%= task.priority %></td>
            <td><%= task.status %></td>
            <td><%= task.deadline %></td>
            <td>
              <% if can? :read, task %>
                <%= link_to 'Show', task %>
              <% end %>
            </td>
            <td>
              <% if can? :update, task %>
                <%= link_to 'Edit', edit_task_path(task) %>
              <% end %>
            </td>
            <td>
              <% if can? :destroy, task %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!--box-body-->
</div><!--box-->

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>User:</strong>
  <%= @task.user.full_name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @task.details %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<% if can? :update, @task %>
  <%= link_to 'Edit', edit_task_path(@task) %> |
<% end %>
<%= link_to 'Back', tasks_path %>